/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package daytrader.gui;

import daytrader.historicRequestSystem.HistoricRequestProcessingSystem;
import daytrader.interfaces.observerpattern.IObserver;
import static java.lang.Thread.sleep;
import static java.lang.Thread.yield;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Roy
 */
public class HistoricAccRequestPendingDisplay extends javax.swing.JPanel implements IObserver {
    
    private HistoricRequestProcessingSystem model;
    private AtomicBoolean blnDoUpdate;
    private Thread updater;

    /**
     * Creates new form HistoricAccRequestPendingDisplay
     */
    public HistoricAccRequestPendingDisplay() {
        initComponents();
        this.blnDoUpdate = new AtomicBoolean(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAccName = new javax.swing.JLabel();
        lblPending = new javax.swing.JLabel();

        lblAccName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAccName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccName.setText("Held in pending queue:");

        lblPending.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPending.setText("0");
        lblPending.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAccName, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(lblPending, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAccName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPending, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAccName;
    private javax.swing.JLabel lblPending;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        this.blnDoUpdate.set(true);
    }
    
    private void refreshDisplay() {
        Integer pendingRequestCount = this.model.getPendingRequestCount();
        lblPending.setText(pendingRequestCount.toString());
    }
    
    @Override
    public void addNotify() {
        super.addNotify(); //To change body of generated methods, choose Tools | Templates.
        this.startMonitorThread();
    }

    @Override
    public void removeNotify() {
        super.removeNotify();
        if(null != this.updater){
            this.updater.interrupt();
            this.updater = null;
        }
    }
    
    private void startMonitorThread(){
        if(null != this.updater){
            this.updater.interrupt();
            this.updater = null;
        }
        this.updater = new HistoricAccRequestPendingDisplay.Updater();
        this.updater.start();
    }

    /**
     * @param model the model to set
     */
    public void setModel(HistoricRequestProcessingSystem model) {
        this.model = model;
    }
    
    private class Updater extends Thread {

        @Override
        public void run() {
            while (!this.isInterrupted()) {
                if (blnDoUpdate.get()) {
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            refreshDisplay();
                        }
                    });
                    try {
                        //Wait 1 sec for update
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(HistoricAccountRequestDisplay.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                yield();
            }
        }
    }
}
