/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package daytrader.gui;

import daytrader.datamodel.DTConstants;
import daytrader.datamodel.RealTimeRunManager;
import daytrader.gui.tables.PutupStatusTable;
import daytrader.gui.tables.PutupStatusTableModel;
import java.util.ArrayList;

/**
 * This panel displays the current status of all running put ups 
 * @author Roy
 */
public class PutupStatusDisplay extends javax.swing.JPanel {
    
    PutupStatusTable tblData;

    /**
     * Creates new form PutupStatusDisplay
     */
    public PutupStatusDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPane = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPane, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblData = new PutupStatusTable();
        scrPane.setViewportView(tblData);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrPane;
    // End of variables declaration//GEN-END:variables

    /**
     * Generates the table to display running put up status
     */
    public void generateStatusDisplay(){
        ArrayList<RealTimeRunManager> runningRec = DTConstants.getRunningRecords2();
        if(null != runningRec){
            PutupStatusTableModel model = PutupStatusTableModel.createModel();
            for(RealTimeRunManager manager : runningRec){
                model.addPutupEntry(manager);
            }
            this.tblData.setModel(model);
        }
    }

}
