/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package daytrader.gui;

import daytrader.datamodel.AbstractGraphPoint;
import daytrader.datamodel.BaseGraph;
import daytrader.datamodel.Putup;
import daytrader.datamodel.RealTimeRunManager;
import daytrader.datamodel.RulesStateEnum;

/**
 * This is the panel that displays the current status of the running put up
 *
 * @author Roy
 */
public class PutupStatusEntry extends javax.swing.JPanel {

    private RealTimeRunManager data;

    /**
     * Creates new form PutupStatusEntry
     */
    public PutupStatusEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPutupName = new javax.swing.JLabel();
        lblCurrState = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblGraph1 = new javax.swing.JLabel();
        lbl5SecBarSize = new javax.swing.JLabel();
        lblGraph2 = new javax.swing.JLabel();
        lblMrkDataSize = new javax.swing.JLabel();
        lblGraph3 = new javax.swing.JLabel();
        lblHistoricDataGraphSize = new javax.swing.JLabel();
        lblPrevDayData = new javax.swing.JLabel();
        lblPrevDaySize = new javax.swing.JLabel();
        lbl5SecBarRunning = new javax.swing.JLabel();
        lbl5SecBarRunning.setOpaque(true);

        setMinimumSize(new java.awt.Dimension(385, 122));

        lblPutupName.setText("A Putup Ticker Code");

        lblCurrState.setText("Current State:");

        lblState.setText("UNKNOWN");

        lblGraph1.setText("5 Sec Bars Graph Size = ");

        lbl5SecBarSize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl5SecBarSize.setText("0");

        lblGraph2.setText("Market Data Graph Size = ");

        lblMrkDataSize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMrkDataSize.setText("0");

        lblGraph3.setText("Historic Data Graph Size = ");

        lblHistoricDataGraphSize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHistoricDataGraphSize.setText("0");

        lblPrevDayData.setText("Previous Days Graph Size =");

        lblPrevDaySize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrevDaySize.setText("0");

        lbl5SecBarRunning.setBackground(new java.awt.Color(255, 102, 102));
        lbl5SecBarRunning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5SecBarRunning.setText("5 Sec Real Time Bars Running");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl5SecBarRunning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPutupName)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrState, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblState, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPrevDayData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGraph2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGraph1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGraph3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl5SecBarSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMrkDataSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHistoricDataGraphSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrevDaySize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPutupName)
                    .addComponent(lblCurrState)
                    .addComponent(lblState))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGraph1)
                    .addComponent(lbl5SecBarSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGraph2)
                    .addComponent(lblMrkDataSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGraph3)
                    .addComponent(lblHistoricDataGraphSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrevDayData)
                    .addComponent(lblPrevDaySize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl5SecBarRunning)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl5SecBarRunning;
    private javax.swing.JLabel lbl5SecBarSize;
    private javax.swing.JLabel lblCurrState;
    private javax.swing.JLabel lblGraph1;
    private javax.swing.JLabel lblGraph2;
    private javax.swing.JLabel lblGraph3;
    private javax.swing.JLabel lblHistoricDataGraphSize;
    private javax.swing.JLabel lblMrkDataSize;
    private javax.swing.JLabel lblPrevDayData;
    private javax.swing.JLabel lblPrevDaySize;
    private javax.swing.JLabel lblPutupName;
    private javax.swing.JLabel lblState;
    // End of variables declaration//GEN-END:variables

    public void refreshDisplay() {
        if (null != this.data) {
            Putup myPutup = this.data.getMyPutup();
            RulesStateEnum currentState = this.data.getCurrentState();
            if (null != currentState) {
                lblState.setText(currentState.toString());
            } else {
                lblState.setText("UNKNOWN STATE");
            }
            lblPutupName.setText(myPutup.getTickerCode());
            lbl5SecBarSize.setText(Integer.toString(this.data.getGraph5SecBars().size()));
            lblMrkDataSize.setText(Integer.toString(this.data.getGraphReqMarketData().size()));
            lblHistoricDataGraphSize.setText(Integer.toString(this.data.getGraphHistoricData().size()));
            BaseGraph<AbstractGraphPoint> prevDayGraph = this.data.getGraph5SecBars().getPrevDayGraph();
            if (null != prevDayGraph) {
                lblPrevDaySize.setText(Integer.toString(this.data.getGraph5SecBars().getPrevDayGraph().size()));
            } else {
                lblPrevDaySize.setText("0");
            }
            if(this.data.isGetting5SecBars()){
                lbl5SecBarRunning.setBackground(new java.awt.Color(153, 255, 153));
            }else{
                lbl5SecBarRunning.setBackground(new java.awt.Color(255, 102, 102));
            }
        } else {
            lblState.setText("NO PUTUP FOUND");
            lblPutupName.setText("NO PUTUP FOUND");
            lbl5SecBarSize.setText("0");
            lblMrkDataSize.setText("0");
            lblHistoricDataGraphSize.setText("0");
            lblPrevDaySize.setText("0");
            lbl5SecBarRunning.setBackground(new java.awt.Color(255, 102, 102));
        }
    }

    /**
     * @param data the data to set
     */
    public void setData(RealTimeRunManager data) {
        this.data = data;
        this.refreshDisplay();
    }
}
