/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package daytrader.gui;

import daytrader.datamodel.Putup;
import daytrader.interfaces.observerpattern.IObserver;

/**
 *
 * @author Roy
 */
public class YLineLoadingDisplay extends javax.swing.JPanel implements IObserver {
    
    private Putup model;

    /**
     * Creates new form YLineLoadingDisplay
     */
    public YLineLoadingDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTicker = new javax.swing.JLabel();
        lblProgress = new javax.swing.JLabel();

        lblTicker.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTicker.setText("UNKNOWN");

        lblProgress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblProgress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProgress.setText("UNKNOWN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTicker)
                .addGap(18, 18, 18)
                .addComponent(lblProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTicker)
                .addComponent(lblProgress))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblTicker;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        if(null != this.model){
            this.lblTicker.setText(this.model.getTickerCode());
            this.lblProgress.setText(this.model.getYLineStatus().toString());
        }
    }

    /**
     * @param model the model to set
     */
    public void setModel(Putup model) {
        this.model = model;
        this.model.registerObserver(this);
        this.update();
    }
    
    
}
